env:
  browser: true
  commonjs: true
  es2020: true
extends:
  - google
parserOptions:
  ecmaVersion: 11
ignorePatterns: ["src/main/webapp/js/FileSaver.js", "src/main/webapp/js/jszip-utils.min.js", "src/main/webapp/js/jszip.min.js"]
rules: {
  'indent': [
      'error', 4, {
        'CallExpression': {
          'arguments': 1,
        },
        'FunctionDeclaration': {
          'body': 1,
          'parameters': 1,
        },
        'FunctionExpression': {
          'body': 1,
          'parameters': 1,
        },
        'MemberExpression': 1,
        'ObjectExpression': 1,
        'SwitchCase': 1,
        'ignoredNodes': [
          'ConditionalExpression',
        ],
      },
    ],
}
